command-to-run: ${COMMAND_TO_RUN}
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      data-source-properties:
        stringtype: unspecified
      maximum-pool-size: 1